### ISSUE TITLE
[Feature Request] Add alias (description) as the third field

### ISSUE THREAD

**Issue by emisjerry** [anselmwang/obsidian-key-sequence-shortcut#1]
Because in the dialog, the QuickAdd commands are hard to read:

![image](https://user-images.githubusercontent.com/131511/156535218-34b8746c-7230-4c7e-8ab0-0214cd2b9d4d.png)

Could it be posibble there's a third field, and in dialog shows this field? For example:

* config:
```
adm	quickadd:choice:27316daa-cd2d-4763-ab0f-162d67212a11quickadd:choice:31fbd691-2f4a-471f-ae5e-3c583b0538ba "Insert Admonitions via QuickAdd#1"
```

* in selection dialog shows(If there's no the third field, uses the 2nd field instead):

adm: Insert Admonitions via QuickAdd#1
mv: file-explorer:move-file

May i use Chinese next time? Thanks.

**Comment by anselmwang** [comment]
Just add the feature with 8b396e2a2ff26e6fe280486e57594cf9c1f8ecf2.
Could you help to verify? If it works, I can close this issue.

Please feel free to use Chinese.

**Comment by emisjerry** [comment]
Could you please place new main.js to a new brach that i can clone?

Sorry i'm not familar with TypeScript and its development environment.

**Comment by anselmwang** [comment]
Here it is. Please remove the ".txt" suffix from file name.
[main.js.txt](https://github.com/anselmwang/obsidian-key-sequence-shortcut/files/8183532/main.js.txt)

**Comment by emisjerry** [comment]
It works perfect! 🙏

另外一提，在Obsidian裡按Tab不會在游標位置插入，而會變成內縮，因此在Obsidian裡編輯kssrc.md會需要自己去變更Tab字元。例如 (| 是輸入游標位置):

aa| 

按Tab後會變成List的內縮(Indent):

        aa|

而不是想要的:
```
aa        |
```
![image](https://user-images.githubusercontent.com/131511/156714426-3dd28ac3-d9e8-4080-a878-0db9878db2c1.png)

**Comment by anselmwang** [comment]
Thanks for your feedback. I guess what you mentioned is the effect of a plugin. I didn't experience this issue.

Originally, I want to avoid this problem by using space as the separator, however, both command id and description often have spaces inside. 

How about we close this issue for now? In case you find a good solution, please feel free to open new issue.

**Comment by emisjerry** [comment]
Sure, please close this issue. Thanks.
