### ISSUE TITLE
How does this plugin compare with its counterparts ?

### ISSUE THREAD

**Issue by ngirard** [anselmwang/obsidian-key-sequence-shortcut#11]
There are currently 4 plugins that apparently provide the same functionality.
Unfortunately, there is currently no information that would help to make an informed choice among them.
Could you please explain how your plugin differs from its counterparts ?

Here are the information I gathered about the aforementioned plugins, yours included:

**Chorded hotkeys**
DL:: 261
Updated:: 3 months ago
Issues:: 2
Commits:: 9
Version:: 1.0.0
obsidian://show-plugin?id=obsidian-chorded-hotkeys
https://github.com/ConnorMeyers/obsidian-chorded-hotkeys

**Sequence hotkeys**
DL:: 954
Updated:: 3 months ago
Issues:: 9
Commits:: 60
Version:: 0.5.1
obsidian://show-plugin?id=obsidian-sequence-hotkeys
https://github.com/moolmanruan/obsidian-sequence-hotkeys

**Hotkeys chords**
DL:: 446
Updated:: a year ago
Issues:: 2
Commits:: 47
Version:: 0.1.0
obsidian://show-plugin?id=obsidian-hotkeys-chords
https://github.com/trenta3/obsidian-hotkeys-chords

**Key sequence shortcut**
DL:: 840
Updated:: a year ago
Issues:: 6
Commits:: 18
Version:: 2.0.2
obsidian://show-plugin?id=obsidian-key-sequence-shortcut
https://github.com/anselmwang/obsidian-key-sequence-shortcut

Thanks very much in advance !
Cheers

**Comment by anselmwang** [comment]
**Key sequence shortcut** 
- Type Ctrl-M to trigger, then support character sequence like "phw" as hotkey.
- Auto command suggestion to help memorize
- text based configuration

**Sequence hotkeys** , **Hotkeys chords**
- support arbitrary hotkey sequences, so you can use key sequence like "Alt-b Ctrl-a p h w" 
- No command suggestion
- UI based configuration

**Chorded hotkeys**
- Support character sequence as hotkey.
- Type faster than average to trigger. This triggering method sounds strange to me, I haven't use the plugin in my daily life, not sure how well it works.

**Comment by ngirard** [comment]
Thanks, @anselmwang, much appreciated !
