### ISSUE TITLE
[Feature Request] Using with slash command

### ISSUE THREAD

**Issue by emisjerry** [anselmwang/obsidian-key-sequence-shortcut#2]
Could it be posibble that we can use these shortcuts with Slash command, which without selection dialog?

For example:

/xh	-> will trigger editor:set-heading
/xl	-> will trigger editor:toggle-bullet-list

**Comment by anselmwang** [comment]
I might need some background. 
- What is slash command and where do we enter it?
- Do we need type "enter" after each command?

**Comment by anselmwang** [comment]
Thanks for your suggestion. 

I am not sure I understand correctly. Do you want the plugin can work together with slash?

Or do you mean to implement similar functionality as slash? That when typing slash, trigger key sequence menu instead of obsidian command pallette?

**Comment by emisjerry** [comment]
FYI: https://forum.obsidian.md/t/obsidian-release-v0-12-17/25270

Type '/' in Obsidian editor, it will popup commands dialog.

I wonder could it be possible that this plugin integrates into core slash command to get better operations.

**Comment by anselmwang** [comment]
I guess we can't reuse '/', because the logic is conflicting. When a user press '/', should we trigger system command palette or key sequence menu?

**Comment by emisjerry** [comment]
Yes, i mean "integrates". If this is imposible to do, that's OK.

Thanks,

**Comment by anselmwang** [comment]
Get it. Thanks :)
