### ISSUE TITLE
FR: Can the plugin suppose the first alphabet ignore?

### ISSUE THREAD

**Issue by YIRU69** [anselmwang/obsidian-key-sequence-shortcut#4]
Thanks for you plugin. It helps me a lot and make me have a high efficiency on my phone.
And I have a problem about it. 
My keyboard apply "A letter of alphabet capital letter" on phone, 
So I have to switch capital letter when I use Key sequence shortcut.
Can the plugin ignore the first alphabet?
Thank you and hope your reply!

**Comment by anselmwang** [comment]
I have been thinking your problem for a while. A simple solution would be just by configuration. In your configuration, set the first character of your key sequence shortcut to be uppercase. Then the auto uppercase behavior of your input method just fit with your configuration perfectly.

**Comment by YIRU69** [comment]
@anselmwang 说中文吧。。首先谢谢你的回复！
第一，我现在的方案的确是把首字母的大写取消掉了，但在日常的打字这样就很不方便
第二，如果这个功能对插件有一定好处，我希望作者可以加一下，求求啦大佬
第三，我建议插件有一个模糊的搜索，像官方本身的命令一样，可以通过描述的自动搜索
当然如果容易实现现在作者能抽时间做一下，这样的意义在于我在忘记的命名的时候，可以辅助我去选择命名
第四， 可以添加一些比较快捷命名，支持一些链接的跳转，比如配合advance-url这种来使用

**Comment by anselmwang** [comment]
1. 关于1和2，我不是建议你取消首字母大写，我是建议你在自己的配置中让常用key sequence就是首字母大写的，比如
```
Xh	editor:set-heading
```
这样你的输入法就不会成为障碍了。

2. 这个插件的目的是和fuzzy match有所不同，这个插件的目的是确定性、不假思索的使用。频率高的命令一两天就记住了，频率不高的命令建议不要放进配置。你可以使用`Command Palette--`这个插件。

3. 这个插件的目的是给已有命令一个快捷访问方法，插件自身不应该提供任何额外的命令。如果你需要“跳转到链接”这样的命令，有很多插件已经支持了，比如`Jump to link`.

**Comment by YIRU69** [comment]
@anselmwang  谢谢回复，我明白了
