### ISSUE TITLE
FR: support using a slash to open the KSS command palette when switching off the core plugin "Slash commands"

### ISSUE THREAD

**Issue by XMB-7** [anselmwang/obsidian-key-sequence-shortcut#5]
Like what Notion does and what Obsidian also has achieved via a core plugin called "Slash commands".
Is it possible that when I switch off this core plugin, I was allowed to just type in a slash to popup the KSS command palette?  Meanwhile, hoping the corresponding hotkey like "ctrl+shift+p" that I've set also takes effect.
BTW, thanks a lot for your effort on this awesome plugin.
![图片](https://user-images.githubusercontent.com/65625632/161735136-cb88f8b0-2d38-47ca-9554-c256fd167819.png)

**Comment by anselmwang** [comment]
I tried but didn't figure out a solution for this issue. :( 
My Obsidian plugin development knowledge is poor ..
