### ISSUE TITLE
FR: use a delimiter other than `tab`

### ISSUE THREAD

**Issue by chrisgrieser** [anselmwang/obsidian-key-sequence-shortcut#7]
reason being that you cannot properly enter a tab in Obsidian – it will indent the line instead of inserting the needed tab. And having to open the document somewhere else is quite clunky. Maybe use `|` or `;`?

**Comment by anselmwang** [comment]
Choosing TAB as the separator is a trade-off. I understand we can't easily enter a TAB in Obsidian, it will indent the line. However, the last column in config file is "description" which can easily contain characters like ";" or "|" or space. Considering this, I still choose TAB. To enter it, I simply type TAB in any other editors (e.g. Notepad on Windows platform) ans paste it into Obsidian.
