### ISSUE TITLE
[FR] show/hide all shortcuts on empty prompt

### ISSUE THREAD

**Issue by ChasKane** [anselmwang/obsidian-key-sequence-shortcut#8]
# Motivation
When I hit my shortcut to bring up the key sequence prompt, it's easy to be distracted by all the options that show up in the menu.

# Suggested change
Add a toggle to the settings menu that would disable these suggestions on an as-yet empty string/before typing any characters. or perhaps a 3 way slider (or however's easiest to represent the ternary), the middle option of which would be to only show available single-character shortcuts.

# Notes
I suspect this one's simple, so I might make a PR for it in the next few weeks.

**Comment by anselmwang** [comment]
I have very limited knowledge on Obsidian plugin development, that is why I adopt the simplest solution now. Feel free to create your PR. 

Thanks a lot!
