### ISSUE TITLE
Insensitivity to the selected keyboard layout

### ISSUE THREAD

**Issue by tonygrr** [anselmwang/obsidian-key-sequence-shortcut#9]
Is it possible to make the keys you press when the palette is open to be insensitive to the selected keyboard layout?

I use two keyboard layouts: Russian and English. This fact gives me a hard time when using this plugin, because if you open the palette when the Russian keyboard layout is active, the keyboard shortcuts recorded for the English layout does not work. I made sure that you can duplicate the commands for each keyboard layout, but it's confusing and takes a while to figure out which keys you should press depending on the selected layout and the combinations offered in the palette.

**Comment by anselmwang** [comment]
Sorry I have no idea how to implement this...
